### ISSUE TITLE
Comprimentos Mínimos

### ISSUE THREAD

**Issue by bento-martins** [dgterritorio/recart-scripts-sql#1]
Olá,

Disponibilizaram scripts para obter os elementos que não são possuem o comprimento mínimo de 0.20 m para o NdD1, nomeadamente o comprimento_minimo_3d_ndd1.sql e o comprimento_minimo_2d_ndd1.sql.
Não encontramos referência a este valor de 0.20 m em nenhum documento. Onde posso encontrar esta informação? Para o NdD2 qual o valor que se aplica?

Muito obrigado. Continuação de um bom trabalho.

**Comment by hsilva321** [comment]
Boa tarde,

O valor para NdD2 é 1 metro.

Os elementos de comprimento inferior as valores referidos praticamente não terem representação às escala equivalentes e prejudicam a leitura da cartografia através da sua sobrecarga.

Obrigado por ter colocado a sua dúvida, também pode ser utíl para outros utilizadores.
Com os melhores cumprimentos,

**Comment by bento-martins** [comment]
Muito obrigado pelo esclarecimento. Iremos ter em consideração estes valores. 
Cumprimentos
