### ISSUE TITLE
Geometria desconhecida - info3d Consistência 

### ISSUE THREAD

**Issue by sandraedia** [dgterritorio/recart-scripts-sql#2]
Boa tarde,

Ao executar o script 
"info3d_consistencia_pontos" retorna o erro:
ERROR: Unknown geometry type: 14 - Triangle SQL state: XX000
Na geração do TIN não há problema. Mas o tipo de geometria "triangulo" é sempre inválido.
Obrigada

**Comment by hsilva321** [comment]
Boa tarde,

Quando gerar o TIN, utilize a flags=0 em ST_DelaunayTriangles(geometry g1, float tolerance, int4 flags)
Assim retorna uma coleção de polígonos e já não vai ter problemas com a gometria Triangle.

https://postgis.net/docs/ST_DelaunayTriangles.html

**Comment by sandraedia** [comment]
Resolvido!
Obrigada
